language: node_js
node_js:
- 15.14.0
cache:
  directories:
    - node_modules
install:
- npm install
script:
- npm run build
deploy:
- provider: script
  script: npm run deploy
  skip_cleanup: true
  on:
    all_branches: true

env:
  global:
    - NODE_ENV: 'production'
