import React from 'react';

export const programs = {
  tanachstudy: {
    mainColor: '#009FC1',
    secondaryColor: '#E5F3F7',
    tertiaryColor: '#039BE5',
    complementaryColor: '#FFB023',
    logo: 'https://cdn.tanachstudy.com/assets/images/logo.png',
    linkPrefix: 'tanach-study',
    backgroundClass: 'tsblue',
    textClass: 'tsblue-text',
    podcastURL: 'https://podcasts.apple.com/us/podcast/tanach-study/id930200652',
  },
  mishnastudy: {
    mainColor: '#950010',
    secondaryColor: '#F2E1E2',
    tertiaryColor: '#D33447',
    complementaryColor: '#2AAD5F',
    logo: 'https://cdn.tanachstudy.com/assets/images/mishna-study-logo.png',
    linkPrefix: 'mishna-study',
    backgroundClass: 'msred',
    textClass: 'msred-text',
    podcastURL: 'https://podcasts.apple.com/us/podcast/mishna-study/id1458633885',
  },
  haftarastudy: {
    mainColor: '#EE5A24',
    secondaryColor: '#FFE6C4',
    tertiaryColor: '#FFA18B',
    complementaryColor: '#AC3019',
    logo: 'https://cdn.tanachstudy.com/assets/images/haftara-study-logo.png',
    linkPrefix: 'haftara-study',
    backgroundClass: 'hsorange',
    textClass: 'hsorange-text',
    podcastURL: 'https://podcasts.apple.com/us/podcast/tanach-study/id930200652',
  },
  parashastudy: {
    mainColor: '#127E36',
    secondaryColor: '#E4F0E5',
    tertiaryColor: '#45AA67',
    complementaryColor: '#AC3019',
    logo: 'https://cdn.tanachstudy.com/assets/images/parasha-study-logo.png',
    linkPrefix: 'parasha-study',
    backgroundClass: 'psgreen',
    textClass: 'psgreen-text',
    podcastURL: 'https://podcasts.apple.com/us/podcast/parasha-study/id1459797702',
  },
  parashastudyplus: {
    mainColor: '#00806f',
    secondaryColor: '#E4F0E5',
    tertiaryColor: '#45AA67',
    complementaryColor: '#AC3019',
    logo: 'https://cdn.tanachstudy.com/assets/images/parasha-study-plus-logo.png',
    linkPrefix: 'parasha-plus-study',
    backgroundClass: 'psplusgreen',
    textClass: 'psplusgreen-text',
    podcastURL: 'https://podcasts.apple.com/us/podcast/parasha-study/id1459797702',
  },
  moadimstudy: {
    mainColor: '#EEDA22',
    secondaryColor: '#FBF7D0',
    tertiaryColor: '#FFE700',
    complementaryColor: '#5823A2',
    logo: 'https://cdn.tanachstudy.com/assets/images/moadim-study-logo.png',
    linkPrefix: 'moadim-study',
    backgroundClass: 'moadimyellow',
    textClass: 'moadimyellow-text',
    podcastURL: 'https://podcasts.apple.com/us/podcast/tanach-study/id930200652',
  },
};

export const ProgramContext = React.createContext(programs.tanachstudy);
