name: Build & Upload Gatsby

on:
  push:
    branches: [ master ]
  schedule:
    - cron: '10 2,14 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 20.0.0
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - run: yarn install --frozen-lockfile
    - run: yarn run build
      env:
        API_URL: ${{ secrets.API_URL }}
    - run: yarn run deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
